@startuml
participant participant as Usuario
actor ExtratoAnualComponent as ExtratoAnualComponent
boundary IExtratoAnualTarifaService as extratoAnualService
boundary IClienteService as clienteService
activate ExtratoAnualComponent

ExtratoAnualComponent->ExtratoAnualComponent  : ngOnInit
activate ExtratoAnualComponent #005500
ExtratoAnualComponent->ExtratoAnualComponent :obterExtratoTarifas
activate ExtratoAnualComponent #0055FF
ExtratoAnualComponent  -> clienteService #0055F0: numeroContaSelecionado
ExtratoAnualComponent -> extratoAnualService: carregarListaExtratoAnualTarifasactivate ExtratoAnualComponent
deactivate ExtratoAnualComponent
deactivate ExtratoAnualComponent
deactivate ExtratoAnualComponent
Usuario -> ExtratoAnualComponent  : downloadPdf
activate ExtratoAnualComponent #00FF00

ExtratoAnualComponent  -> clienteService  #0055F0: numeroContaSelecionado
ExtratoAnualComponent -> extratoAnualService : carregarPdfExtratoAnualTarifa
deactivate ExtratoAnualComponent



@enduml
