@startuml 
 autoactivate on 
 participant participant as Usuario
actor  ExtratoAnualComponent as ExtratoAnualComponent
boundary  IExtratoAnualTarifaService as extratoAnualService
boundary  IClienteService as clienteService
ExtratoAnualComponent->ExtratoAnualComponent #005500: ngOnInit 
ExtratoAnualComponent->ExtratoAnualComponent : obterExtratoTarifas 
ExtratoAnualComponent->ExtratoAnualComponent : elementLoading 
ExtratoAnualComponent->ExtratoAnualComponent : numeroContaSelecionado 
ExtratoAnualComponent->ExtratoAnualComponent : clienteService 
ExtratoAnualComponent->ExtratoAnualComponent : extratoTarifas 
ExtratoAnualComponent->ExtratoAnualComponent : carregarListaExtratoAnualTarifas 
ExtratoAnualComponent->ExtratoAnualComponent : extratoAnualService 
ExtratoAnualComponent->ExtratoAnualComponent : errorTarifa 
ExtratoAnualComponent->ExtratoAnualComponent : elementLoading 
Usuario->ExtratoAnualComponent #005500: obterExtratoTarifas 
ExtratoAnualComponent->clienteService : numeroContaSelecionado 
ExtratoAnualComponent->extratoAnualService : carregarListaExtratoAnualTarifas 
ExtratoAnualComponent->ExtratoAnualComponent : numeroContaSelecionado 
ExtratoAnualComponent->ExtratoAnualComponent : clienteService 
ExtratoAnualComponent->ExtratoAnualComponent : carregarPdfExtratoAnualTarifa 
ExtratoAnualComponent->ExtratoAnualComponent : extratoAnualService 
ExtratoAnualComponent->ExtratoAnualComponent : createElement 
ExtratoAnualComponent->ExtratoAnualComponent : href 
ExtratoAnualComponent->ExtratoAnualComponent : download 
ExtratoAnualComponent->ExtratoAnualComponent : click 
Usuario->ExtratoAnualComponent #005500: downloadPdf 
ExtratoAnualComponent->clienteService : numeroContaSelecionado 
ExtratoAnualComponent->extratoAnualService : carregarPdfExtratoAnualTarifa 
@enduml