@startuml 
 participant participant as Usuario
actor  ExtratoAnualComponent as ExtratoAnualComponent
boundary  IExtratoAnualTarifaService as extratoAnualService
boundary  IClienteService as clienteService
Usuario -> ExtratoAnualComponent:ngOnInit
activate ExtratoAnualComponent #005500
ExtratoAnualComponent -> ExtratoAnualComponent:obterExtratoTarifas
activate ExtratoAnualComponent #0055FF
ExtratoAnualComponent -> clienteService:numeroContaSelecionado
ExtratoAnualComponent -> extratoAnualService:carregarListaExtratoAnualTarifas
deactivate ExtratoAnualComponent
deactivate ExtratoAnualComponent
Usuario -> ExtratoAnualComponent:downloadPdf
activate ExtratoAnualComponent #005500
ExtratoAnualComponent -> clienteService:numeroContaSelecionado
ExtratoAnualComponent -> extratoAnualService:carregarPdfExtratoAnualTarifa
deactivate ExtratoAnualComponent
@enduml