@staruml 
 autoactivate on 
 participant participant as Usuario
actor  ExtratoAnualComponent as ExtratoAnualComponent
boundary  IExtratoAnualTarifaService as extratoAnualService
boundary  IClienteService as clienteService
ExtratoAnualComponent->ExtratoAnualComponent : ngOnInit 
undefined->undefined : obterExtratoTarifas 
ExtratoAnualComponent->clienteService : numeroContaSelecionado 
ExtratoAnualComponent->extratoAnualService : carregarListaExtratoAnualTarifas 
ExtratoAnualComponent->clienteService : numeroContaSelecionado 
ExtratoAnualComponent->extratoAnualService : carregarPdfExtratoAnualTarifa 
